sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: npm
install:
  - yarn
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
  - cd public
  - touch CNAME
  - echo 'blog.trycatchyou.com' > CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
